dependencies:
  - python=3.9
  - rasterio=1.2.10
  - geopandas=0.12.2
  - xarray=2023.6.0
  - scipy=1.13.0
  - pip
  - pip:
      - netcdf4==1.6.5
      - rioxarray==0.15.0
      - matplotlib-scalebar==0.7.2